browsers:
    -
      browser: firefox
      browser_version: "20.0"
      os: Windows
      os_version: "7"
    -
      browser: ie
      browser_version: "9.0"
      os: Windows
      os_version: "7"
    -
      browser: chrome
      browser_version: "28.0"
      os: Windows
      os_version: "7"