
name: Remote Test - Muffet

on:
  push:
    branches: 
      - test
      - test_muffet
  workflow_dispatch:

env:
  URL: https://staging.londonparkour.com
  FILENAME: report.yaml

jobs:

  #  ┌───────────────────────────────────────────┐ 
  #  │                                           │░
  #  │                JOB: Muffet                │░
  #  │                                           │░
  #  └───────────────────────────────────────────┘░
  #   ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░


  linkcheck:


    runs-on: ubuntu-18.04
    name: Muffet tests

    steps:

    - name: Check
      env:
        INPUT_URL: https://staging.londonparkour.com
        INPUT_CMD_PARAMS: --buffer-size=8192 --max-connections=10 --color=always --skip-tls-verification
      run: wget -qO- https://raw.githubusercontent.com/ruzickap/action-my-broken-link-checker/v1/entrypoint.sh | bash