
name: Remote Test - BLC

on:
  push:
    branches: 
      - test
      - test_muffet
  workflow_dispatch:

env:
  url: 'https://staging.londonparkour.com'
  results: '/tmp/results.txt'

jobs:

  #  ┌───────────────────────────────────────────┐ 
  #  │                                           │░
  #  │                  JOB: BLC                 │░
  #  │                                           │░
  #  └───────────────────────────────────────────┘░
  #   ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░


  linkcheck:


    runs-on: ubuntu-18.04
    name: BLC tests

    steps:


      - name: download blc
        run: |
          sudo npm install -g npm@latest
          sudo npm install -g broken-link-checker

      # DEBUG with NGROK. 
      - name: Start SSH session
        uses: luchihoratiu/debug-via-ssh@main
        with:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          SSH_PASS: ${{ secrets.NGROK_SSH_PASS }}
          NGROK_REGION: eu


      - name: run blc
        run: |
          sudo blc --input https://staging.londonparkour.com -ro &>> /tmp/results.txt 



      - name: BLC Results
        uses: actions/upload-artifact@v2
        with:
          name: Results File  
          path: /tmp/results.txt


