
name: Test - W3C validator [STAGING]

on:
  push:
    branches: 
      - test
      - test_validator
  workflow_dispatch:

env:
  url: "https://staging.londonparkour.com/sitemap_index.xml"

jobs:

  validator:

    runs-on: ubuntu-latest
    name: Validator tests

    steps:


      - name: checkout repository
        uses: actions/checkout@v2


      # Run CURL On W3C Validator
      - name: Validate
        run: |
          .github/workflows/setup/w3c_validate.sh ${{ env.url }}


      - name: Validate Results
        uses: actions/upload-artifact@v2
        with:
          name: Results File  
          path: /tmp/validator-results.json