
name: Test - W3C validator [STAGING]

on:
  push:
    branches: 
      - test
      - test_validator
  workflow_dispatch:

env:
  url: "https://staging.londonparkour.com"

jobs:

  validator:

    runs-on: ubuntu-latest
    name: Validator tests

    steps:

      # Run CURL On W3C Validator
      - name: Validate
        run: |
          curl "https://validator.w3.org/nu/?out=json&doc=${{ env.url }}" > /tmp/validator-results.json


      - name: Validate Results
        uses: actions/upload-artifact@v2
        with:
          name: Results File  
          path: /tmp/validator-results.json