
name: Remote Test - Muffet

on:
  push:
    branches: 
      - test
      - test_muffet
  workflow_dispatch:


jobs:

  #  ┌───────────────────────────────────────────┐ 
  #  │                                           │░
  #  │                JOB: Muffet                │░
  #  │                                           │░
  #  └───────────────────────────────────────────┘░
  #   ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░


  linkcheck:


    runs-on: ubuntu-18.04
    name: Muffet tests

    steps:

      - name: Check for broken links
        id: link-report
        uses: elliotforbes/broken-link-checker@1.0.2
        with:
          url: "https://staging.londonparkour.com"
          cmd_params: "--exclude=youtube.com --buffer-size=8192 --max-connections=10 --color=always --verbose > /tmp/results.txt"

      - name: Muffet Results
        uses: actions/upload-artifact@v2
        with:
          name: Results File
          path: /tmp/results.txt


      # # DEBUG with NGROK.
      # - name: Start SSH session
      #   uses: luchihoratiu/debug-via-ssh@main
      #   with:
      #     NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      #     SSH_PASS: ${{ secrets.NGROK_SSH_PASS }}
      #     NGROK_REGION: eu