
name: Test - browserstack [STAGING]

on:
  push:
    tags:
      - tests*
      - test_browserstack*
  workflow_dispatch:


env:
  url: 'https://staging.londonparkour.com'
  config: '.github/workflows/setup/browsers.yaml'  
  BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
  BROWSERSTACK_TOKEN: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  

jobs:

  #  ┌───────────────────────────────────────────┐ 
  #  │                                           │░
  #  │            JOB: browserstack              │░
  #  │                                           │░
  #  └───────────────────────────────────────────┘░
  #   ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░


  linkcheck:


    runs-on: ubuntu-latest
    name: browserstack tests

    steps:


      - name: checkout repository
        uses: actions/checkout@v2


      - name: download browserstack
        run: |
          sudo gem install screenshooter


      - name: run browserstack
        run: |
          screenshooter shoot -u ${{ env.url }} -b ${{ env.config }} > /tmp/browserstack-results.txt

      - name: Browserstack Results
        uses: actions/upload-artifact@v2
        with:
          name: Results File  
          path: /tmp/browserstack-results.txt


      # DEBUG with NGROK.
      - name: Start SSH session
        uses: luchihoratiu/debug-via-ssh@main
        with:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          SSH_PASS: ${{ secrets.NGROK_SSH_PASS }}
          NGROK_REGION: eu
