
name: Test - pa11y [STAGING]

on:
  push:
    branches: 
      - test
      - test_pa11y
  workflow_dispatch:


jobs:

  #  ┌───────────────────────────────────────────┐ 
  #  │                                           │░
  #  │                JOB: PA11Y                 │░
  #  │                                           │░
  #  └───────────────────────────────────────────┘░
  #   ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░


  linkcheck:


    runs-on: ubuntu-latest
    name: pa11y tests

    steps:


      - name: download pa11y-ci
        run: |
          sudo npm install -g npm@latest
          sudo npm install -g pa11y-ci


      - name: run blc
        run: |
          set -x
          (pa11y-ci --sitemap https://staging.londonparkour.com/sitemap_index.xml &>> /tmp/pa11y-results.txt) || true



      - name: BLC Results
        uses: actions/upload-artifact@v2
        with:
          name: Results File  
          path: /tmp/pa11y-results.txt


