# Ubuntu-latest versions
# mysql  Ver 8.0.23-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))
# PHP 8.0.3 (cli) (built: Mar  5 2021 07:54:13) ( NTS )

# Interesting links:
# - https://github.com/PrestaShop/PrestaShop/tree/develop/.github/workflows
# - https://github.com/PrestaShop/PrestaShop/blob/develop/.github/workflows/sanity-74.yml
# - https://freek.dev/1590-how-to-use-a-mysql-database-on-github-actions

name: Testing

on:
  push:
    branches: [ test ]
  workflow_dispatch:


env:
  theme:  'wp-theme__londonparkour--v5'
  url:    'http://127.0.0.1'
  shots:  './screenshots'

jobs:

  # Test Job
  test:
    runs-on: ubuntu-18.04
    name: Testing Website Update
    strategy:
      matrix:
        php: [ '7.4' ]
      fail-fast: false


    steps:

      # Checkout repo with submodules
      # https://github.com/marketplace/actions/checkout-submodules 
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'


      # Unlock with git-crypt.
      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}


      # Install Database once decrypted with git-crypt and GPG key.
      # https://freek.dev/1590-how-to-use-a-mysql-database-on-github-actions
      - name: Install Database
        run: |
          mysql -uroot -h127.0.0.1 -e "DROP DATABASE IF EXISTS staging_londonparkour_com"
          mysql -uroot -h127.0.0.1 -e "CREATE DATABASE staging_londonparkour_com"
          mysql -uroot -h127.0.0.1 staging_londonparkour_com < ./wp-content/database/dev_londonparkour_com.sql


      # Taken from: https://github.com/PrestaShop/PrestaShop/blob/develop/.github/workflows/sanity-74.yml
      - name: Setup Apache
        run: sudo bash .github/workflows/setup/setup-apache.sh ${{ github.workspace }} ${{ matrix.php }}


      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv, simplexml


      # Clone wordpress fresh install
      - name: Install Wordpress
        run: |
          curl -O https://wordpress.org/latest.tar.gz
          tar --strip-components=1 -xzvf latest.tar.gz
          rm latest.tar.gz


      # Installing Node for tools
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x  


      # https://github.com/sindresorhus/capture-website-cli
      - name: Install capture-website-cli
        run: |
          npm install --global capture-website-cli 1> /dev/null


      - name: Ownership
        run: |
          ls -la
          sudo chown -Rf www-data:www-data ./


      - name: Screenshot Website
        run: |
          mkdir ${{ env.shots_dir }}
          capture-website ${{ env.url }} --output ${{ env.shots_dir }}/screenshot.jpg --full-page --type=jpeg --quality=0.5
      

      - name: Upload screenshot
        uses: actions/upload-artifact@v2
        with:
          name: screenshot
          path: ${{ env.shots_dir }}

