
name: Remote Test - Muffet

on:
  push:
    branches: 
      - test
      - test_muffet
  workflow_dispatch:


jobs:

  #  ┌───────────────────────────────────────────┐ 
  #  │                                           │░
  #  │                JOB: Muffet                │░
  #  │                                           │░
  #  └───────────────────────────────────────────┘░
  #   ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░


  linkcheck:


    runs-on: ubuntu-18.04
    name: Muffet tests

    steps:


      - name: Check for broken links
        id: link-report
        uses: celinekurpershoek/link-checker@v1.0.1
        with:
          # Required:
          url: 'https://staging.londonparkour.com'
          # optional:
          honorRobotExclusions: false
          ignorePatterns: 'github,google,instagram,youtube'
          recursiveLinks: false # Check all URLs on all reachable pages (could take a while)

      - name: Get the result
        run: |
          echo "${{steps.link-report.outputs.result}}" > /tmp/results.txt


      - name: Muffet Results
        uses: actions/upload-artifact@v2
        with:
          name: Results File
          path: /tmp/results.txt


      # # DEBUG with NGROK.
      # - name: Start SSH session
      #   uses: luchihoratiu/debug-via-ssh@main
      #   with:
      #     NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      #     SSH_PASS: ${{ secrets.NGROK_SSH_PASS }}
      #     NGROK_REGION: eu