# mysql  Ver 8.0.23-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))
# PHP 8.0.3 (cli) (built: Mar  5 2021 07:54:13) ( NTS )

name: Testing

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ test ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


env:
  url:          'https://staging.londonparkour.com'
  destination:  './staging.londonparkour.com.jpg'
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x  

      # https://github.com/sindresorhus/capture-website-cli
      - name: Install capture-website-cli
        run: |
          npm install --global capture-website-cli 1> /dev/null
        

      - name: Screenshot Website
        run: |
          capture-website ${{ env.url }} --output ${{ env.destination }} --full-page --type=jpeg --quality=0.5


      - name: what?
        run: |
          ls -la
      

      - name: Upload screenshot
        uses: actions/upload-artifact@v2
        with:
          name: screenshot
          path: ${{ env.destination }}

