# Ubuntu-latest versions
# mysql  Ver 8.0.23-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))
# PHP 8.0.3 (cli) (built: Mar  5 2021 07:54:13) ( NTS )

# Interesting links:
# - https://github.com/PrestaShop/PrestaShop/tree/develop/.github/workflows
# - https://github.com/PrestaShop/PrestaShop/blob/develop/.github/workflows/sanity-74.yml
# - https://freek.dev/1590-how-to-use-a-mysql-database-on-github-actions

  #  ┌───────────────────────────────────────────┐ 
  #  │                                           │░
  #  │              JOB: LIGHTHOUSE              │░
  #  │                                           │░
  #  └───────────────────────────────────────────┘░
  #   ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

name: Test - Lighthouse [CI]

on:
  push:
    branches: 
      - test
      - test_lighthouse
  workflow_dispatch:


jobs:

  lighthouse_001:

    runs-on: ubuntu-latest
    name: Lighthouse 001 - https://staging.londonparkour.com

    steps:

      - uses: actions/checkout@v2
      - name: Run Lighthouse on url
        uses: treosh/lighthouse-ci-action@v7
        with:
          urls: |
            https://staging.londonparkour.com
          uploadArtifacts: true
          configPath: './.github/workflows/setup/lighthouse-config.json'




  lighthouse_002:

    runs-on: ubuntu-latest
    name: Lighthouse 002 - https://staging.londonparkour.com/classes

    steps:

      - uses: actions/checkout@v2
      - name: Run Lighthouse on url
        uses: treosh/lighthouse-ci-action@v7
        with:
          urls: |
            https://staging.londonparkour.com
          uploadArtifacts: true
          configPath: './.github/workflows/setup/lighthouse-config.json'
