
name: Remote Test - Muffet

on:
  push:
    branches: 
      - test
      - test_muffet
  workflow_dispatch:

env:
  URL: https://staging.londonparkour.com
  FILENAME: report.yaml

jobs:

  #  ┌───────────────────────────────────────────┐ 
  #  │                                           │░
  #  │                JOB: Muffet                │░
  #  │                                           │░
  #  └───────────────────────────────────────────┘░
  #   ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░


  linkcheck:


    runs-on: ubuntu-18.04
    name: Muffet tests

    steps:

      - name: Check
        uses: ruzickap/action-my-broken-link-checker@v1.0.3
        with:
          url: https://staging.londonparkour.com
          cmd_params: "--one-page-only --color=always --skip-tls-verification --limit-redirections=5 --timeout=20"  # Check just one page