
name: Remote Test - Muffet

on:
  push:
    branches: 
      - test
      - test_muffet
  workflow_dispatch:

env:
  url: 'https://staging.londonparkour.com'
  results: '/tmp/results.txt'

jobs:

  #  ┌───────────────────────────────────────────┐ 
  #  │                                           │░
  #  │                JOB: Muffet                │░
  #  │                                           │░
  #  └───────────────────────────────────────────┘░
  #   ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░


  linkcheck:


    runs-on: ubuntu-18.04
    name: Muffet tests

    steps:


      - name: download muffet
        cmd: |
          curl -L https://github.com/raviqqe/muffet/releases/download/v2.4.1/muffet_2.4.1_Linux_x86_64.tar.gz | tar zx
          sudo chmod +x muffet

      - name: run muffet
        cmd: | 
          muffet ${{ env.url }} --buffer-size=8192 --max-connections=10 --color=always --skip-tls-verification > ${{ env.results }}


      - name: Muffet Results
        uses: actions/upload-artifact@v2
        with:
          name: Results File  
          path: /tmp/results.txt


      # # DEBUG with NGROK. 
      # - name: Start SSH session
      #   uses: luchihoratiu/debug-via-ssh@main
      #   with:
      #     NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      #     SSH_PASS: ${{ secrets.NGROK_SSH_PASS }}
      #     NGROK_REGION: eu