# mysql  Ver 8.0.23-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))
# PHP 8.0.3 (cli) (built: Mar  5 2021 07:54:13) ( NTS )

name: Testing

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ test ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# GPG Key : https://stackoverflow.com/questions/61096521/how-to-use-gpg-key-in-github-actions
env:
  theme:    'wp-theme__londonparkour--v5'

    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checkout repo with submodules
      # https://github.com/marketplace/actions/checkout-submodules 
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Take photo of staging
        uses: JonathanTreffler/full-website-screenshot-action@v1.0
        with:
          url: https://staging.londonparkour.com
          destination: ./staging.londonparkour.com.png


      - name: what?
        run: |
          ls -la
      

      - name: Upload screenshot
        uses: actions/upload-artifact@v2
        with:
          name: screenshot
          path: ./staging.londonparkour.com.png

