# Ubuntu-latest versions
# mysql  Ver 8.0.23-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))
# PHP 8.0.3 (cli) (built: Mar  5 2021 07:54:13) ( NTS )

# Interesting links:
# - https://github.com/PrestaShop/PrestaShop/tree/develop/.github/workflows
# - https://github.com/PrestaShop/PrestaShop/blob/develop/.github/workflows/sanity-74.yml
# - https://freek.dev/1590-how-to-use-a-mysql-database-on-github-actions

  #  ┌───────────────────────────────────────────┐ 
  #  │                                           │░
  #  │              JOB: LIGHTHOUSE              │░
  #  │                                           │░
  #  └───────────────────────────────────────────┘░
  #   ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

name: Test - Lighthouse [CI]

on:
  push:
    branches: 
      - test
      - test_lighthouse
  workflow_dispatch:


jobs:

  lighthouse_001:

    runs-on: ubuntu-latest
    name: Lighthouse 001 - https://staging.londonparkour.com

    steps:

      - uses: actions/checkout@v2
      - name: Run Lighthouse on url
        uses: treosh/lighthouse-ci-action@v7
        with:
          urls: |
            https://staging.londonparkour.com
          uploadArtifacts: true
          configPath: './.github/workflows/setup/lighthouse-config.json'



  lighthouse_002:

    runs-on: ubuntu-latest
    name: Lighthouse 002 - https://staging.londonparkour.com/classes

    steps:

      - uses: actions/checkout@v2
      - name: Run Lighthouse on url
        uses: treosh/lighthouse-ci-action@v7
        with:
          urls: |
            https://staging.londonparkour.com
          uploadArtifacts: true
          configPath: './.github/workflows/setup/lighthouse-config.json'


  upload:


    runs-on: ubuntu-latest
    name: Upload to github actions
    needs: [lighthouse_001, lighthouse_002]

    steps:

      - uses: actions/checkout@v2

      - name: Download lighthouse results
        uses: actions/download-artifact@v2
        with:
          name: lighthouse-results

      - name: Move into build folder
        run: |
          sudo mkdir ./public
          sudo mv *.html ./public
          sudo mv ./.github/workflows/setup/github_pages_index.sh ./public
          cd ./public
          sudo ./github_pages_index.sh

      # DEBUG with NGROK.
      # - name: Start SSH session
      #   uses: luchihoratiu/debug-via-ssh@main
      #   with:
      #     NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      #     SSH_PASS: ${{ secrets.NGROK_SSH_PASS }}
      #     NGROK_REGION: eu

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
